language: node_js
node_js:
  - '14'
services:
  - postgresql
before_script:
  - psql -c 'create database jobly_test;' -U postgres
  - psql < jobly.sql
install:
- npm install
- npm install --save-dev jest
script:
- npm test